services:
  discord_discourse:
    image: ghcr.io/wickedyoda/discord_discourse:latest
    container_name: discord_discourse
    restart: unless-stopped
    env_file:
      - .env
    pull_policy: always