services:
  discord_discourse:
    container_name: discord_discourse
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    image: discord_discourse:local
    restart: unless-stopped
    env_file:
      - .env